<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>dhcpd.conf</string>
	</array>
	<key>name</key>
	<string>ISC DHCPD</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.dhcpd</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.dhcpd</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(zone|host|class|pool|key)\s([^{]+) </string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.dhcpd</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.dhcpd</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.dhcpd</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.dhcpd</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(subnet)\s([^\s]+)\s(netmask)\s([^\s]+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.dhcpd</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.dhcpd</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(authoritative|primary|next-server|filename|ignore|algorithm|secret|log-facility|include|range|key|[a-z]+-lease-time)\s*(.*);?</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.dhcpd</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.dhcpd</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(hardware ethernet|fixed-address)\s([^;]*);</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.dhcpd</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.dhcpd</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(ddns-[a-z-]+)\s([^;]+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.dhcpd</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.dhcpd</string>
				</dict>
			</dict>
			<key>match</key>
			<string>((?:option|range|host)\s+[a-z-]+)\s*([^;]*);</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.dhcpd</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.dhcpd</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([^ ]+)\s+(on|off|true|false)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.dhcpd</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.dhcpd</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(allow|deny)\s+([^ ]+)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*;.*</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*#.*</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*#+</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\[.*\]</string>
			<key>name</key>
			<string>string</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.dhcpd</string>
	<key>uuid</key>
	<string>a9a80b1f-9bc9-4fe6-a723-116a297e9bed</string>
</dict>
</plist>
